//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeopardy.Core.Localization.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocaleCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jeopardy.Core.Localization.Locales.LocaleCommon", typeof(LocaleCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embedded.
        /// </summary>
        public static string ContentAccessType_Embedded {
            get {
                return ResourceManager.GetString("ContentAccessType_Embedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string ContentAccessType_Link {
            get {
                return ResourceManager.GetString("ContentAccessType_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ContentType_Image {
            get {
                return ResourceManager.GetString("ContentType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        public static string ContentType_Sound {
            get {
                return ResourceManager.GetString("ContentType_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ContentType_Text {
            get {
                return ResourceManager.GetString("ContentType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string ContentType_Video {
            get {
                return ResourceManager.GetString("ContentType_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string Enum_Undefined {
            get {
                return ResourceManager.GetString("Enum_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content access type.
        /// </summary>
        public static string Question_ContentAccessType {
            get {
                return ResourceManager.GetString("Question_ContentAccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Question_ContentPath {
            get {
                return ResourceManager.GetString("Question_ContentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        public static string Question_ContentType {
            get {
                return ResourceManager.GetString("Question_ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        public static string Question_CorrectAnswer {
            get {
                return ResourceManager.GetString("Question_CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Question_Price {
            get {
                return ResourceManager.GetString("Question_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question type.
        /// </summary>
        public static string Question_QuestionType {
            get {
                return ResourceManager.GetString("Question_QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task description.
        /// </summary>
        public static string Question_TaskDescription {
            get {
                return ResourceManager.GetString("Question_TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction.
        /// </summary>
        public static string QuestionType_Auction {
            get {
                return ResourceManager.GetString("QuestionType_Auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        public static string QuestionType_Cat {
            get {
                return ResourceManager.GetString("QuestionType_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string QuestionType_Simple {
            get {
                return ResourceManager.GetString("QuestionType_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsored.
        /// </summary>
        public static string QuestionType_Sponsored {
            get {
                return ResourceManager.GetString("QuestionType_Sponsored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported locale.
        /// </summary>
        public static string SupportedLocale {
            get {
                return ResourceManager.GetString("SupportedLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string SupportedLocale_English {
            get {
                return ResourceManager.GetString("SupportedLocale_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string SupportedLocale_Russian {
            get {
                return ResourceManager.GetString("SupportedLocale_Russian", resourceCulture);
            }
        }
    }
}
