//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeopardy.Core.Localization.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocaleClient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleClient() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jeopardy.Core.Localization.Locales.LocaleClient", typeof(LocaleClient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set avatar.
        /// </summary>
        public static string AuthControl_SetAvatar {
            get {
                return ResourceManager.GetString("AuthControl_SetAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up identity.
        /// </summary>
        public static string AuthControl_Title {
            get {
                return ResourceManager.GetString("AuthControl_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use identity.
        /// </summary>
        public static string AuthControl_UseIdentity {
            get {
                return ResourceManager.GetString("AuthControl_UseIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AuthControl_Username {
            get {
                return ResourceManager.GetString("AuthControl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to main menu.
        /// </summary>
        public static string Common_BackToMenu {
            get {
                return ResourceManager.GetString("Common_BackToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer question.
        /// </summary>
        public static string GameLobby_Button_Answer {
            get {
                return ResourceManager.GetString("GameLobby_Button_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string GameLobby_Button_Exit {
            get {
                return ResourceManager.GetString("GameLobby_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause game.
        /// </summary>
        public static string GameLobby_Button_Pause {
            get {
                return ResourceManager.GetString("GameLobby_Button_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume game.
        /// </summary>
        public static string GameLobby_Button_Resume {
            get {
                return ResourceManager.GetString("GameLobby_Button_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question answer time (secs).
        /// </summary>
        public static string HostGame_AnswerTime {
            get {
                return ResourceManager.GetString("HostGame_AnswerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create lobby.
        /// </summary>
        public static string HostGame_CreateLobby {
            get {
                return ResourceManager.GetString("HostGame_CreateLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay settings.
        /// </summary>
        public static string HostGame_GameplaySettings {
            get {
                return ResourceManager.GetString("HostGame_GameplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string HostGame_GeneralSettings {
            get {
                return ResourceManager.GetString("HostGame_GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question hanging time (secs).
        /// </summary>
        public static string HostGame_HangingTime {
            get {
                return ResourceManager.GetString("HostGame_HangingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby name.
        /// </summary>
        public static string HostGame_LobbyName {
            get {
                return ResourceManager.GetString("HostGame_LobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby settings.
        /// </summary>
        public static string HostGame_LobbySettings {
            get {
                return ResourceManager.GetString("HostGame_LobbySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max player count.
        /// </summary>
        public static string HostGame_MaxPlayerCount {
            get {
                return ResourceManager.GetString("HostGame_MaxPlayerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack is not selected.
        /// </summary>
        public static string HostGame_PackNotSelected {
            get {
                return ResourceManager.GetString("HostGame_PackNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string HostGame_Password {
            get {
                return ResourceManager.GetString("HostGame_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret question award multiplier.
        /// </summary>
        public static string HostGame_SecretAwardMultiplier {
            get {
                return ResourceManager.GetString("HostGame_SecretAwardMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select quiz pack.
        /// </summary>
        public static string HostGame_SelectPack {
            get {
                return ResourceManager.GetString("HostGame_SelectPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake question max stake multiplier.
        /// </summary>
        public static string HostGame_StakeMultiplier {
            get {
                return ResourceManager.GetString("HostGame_StakeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string LobbyBrowser_Button_Join {
            get {
                return ResourceManager.GetString("LobbyBrowser_Button_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string LobbyBrowser_Button_Refresh {
            get {
                return ResourceManager.GetString("LobbyBrowser_Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current players.
        /// </summary>
        public static string LobbyBrowser_DataGrid_CurrentPlayers {
            get {
                return ResourceManager.GetString("LobbyBrowser_DataGrid_CurrentPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host username.
        /// </summary>
        public static string LobbyBrowser_DataGrid_Hostname {
            get {
                return ResourceManager.GetString("LobbyBrowser_DataGrid_Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby name.
        /// </summary>
        public static string LobbyBrowser_DataGrid_LobbyName {
            get {
                return ResourceManager.GetString("LobbyBrowser_DataGrid_LobbyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max players.
        /// </summary>
        public static string LobbyBrowser_DataGrid_MaxPlayers {
            get {
                return ResourceManager.GetString("LobbyBrowser_DataGrid_MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password protected?.
        /// </summary>
        public static string LobbyBrowser_DataGrid_Password {
            get {
                return ResourceManager.GetString("LobbyBrowser_DataGrid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby browser.
        /// </summary>
        public static string LobbyBrowser_Title {
            get {
                return ResourceManager.GetString("LobbyBrowser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change identity.
        /// </summary>
        public static string MainMenu_ChangeIdentity {
            get {
                return ResourceManager.GetString("MainMenu_ChangeIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host game.
        /// </summary>
        public static string MainMenu_HostGame {
            get {
                return ResourceManager.GetString("MainMenu_HostGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join game.
        /// </summary>
        public static string MainMenu_JoinGame {
            get {
                return ResourceManager.GetString("MainMenu_JoinGame", resourceCulture);
            }
        }
    }
}
