//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeopardy.Core.Localization.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocaleTester {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleTester() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jeopardy.Core.Localization.Locales.LocaleTester", typeof(LocaleTester).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set file.
        /// </summary>
        public static string DataGrid_Actions_SetFile {
            get {
                return ResourceManager.GetString("DataGrid_Actions_SetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MainWindow_Menu_Header_Actions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string MainWindow_Menu_Header_Categories {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string MainWindow_Menu_Header_Categories_Add {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Categories_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected category.
        /// </summary>
        public static string MainWindow_Menu_Header_Categories_DeleteSelected {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Categories_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MainWindow_Menu_Header_File {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MainWindow_Menu_Header_File_New {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string MainWindow_Menu_Header_File_Open {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_Menu_Header_File_Save {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        public static string MainWindow_Menu_Header_File_SaveAs {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MainWindow_Menu_Header_Language {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string MainWindow_Menu_Header_Questions {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add questions column.
        /// </summary>
        public static string MainWindow_Menu_Header_Questions_Add {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Questions_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected questions column.
        /// </summary>
        public static string MainWindow_Menu_Header_Questions_DeleteSelected {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Questions_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string MainWindow_Menu_Header_Rounds {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new round.
        /// </summary>
        public static string MainWindow_Menu_Header_Rounds_Add {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Rounds_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected round.
        /// </summary>
        public static string MainWindow_Menu_Header_Rounds_DeleteSelected {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Rounds_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run validations.
        /// </summary>
        public static string MainWindow_Menu_Header_Validate {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Header_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
    }
}
